version: 1
project:
  name: agentic-action
  adapter: rust_cargo
  runner_os: ubuntu-latest

commands:
  verify:
    - ["cargo", "test", "--color", "never"]
  format:
    - ["cargo", "fmt", "--all"]
  lint:
    - ["cargo", "clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]

policy:
  max_attempts: 2
  max_changed_files: 5
  max_changed_lines: 200
  allowed_paths:
    - "src/**"
    - "tests/**"
  blocked_paths:
    - ".github/**"
    - "infra/**"
  command_allowlist:
    - "cargo"
    - "npm"
    - "pnpm"
    - "yarn"
  pr:
    title_prefix: "[Agentic-CI] Fix"
    labels: ["agentic-ci", "auto-fix"]
